In [21]:
import numpy as np

## NUMPY INDEXING AND SLICING OF VECTORS

In [22]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [24]:
arr[4]

15

## NUMPY INDEXING AND SLICING OF MATRIX

In [25]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [26]:
slice = arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [27]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

## BOOLEAN INDEXING

In [28]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
bool_index = arr %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [30]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])