In [43]:
import numpy as np

## ***Array Operations***

Arithmatic Operation

In [44]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [45]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [46]:
a1-a2

array([-5, -5, -5, -5, -5])

In [47]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [48]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [49]:
a1//a2

array([0, 0, 0, 0, 0])

In [50]:
a1%a2

array([1, 2, 3, 4, 5])

In [51]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [52]:
a1*2

array([ 2,  4,  6,  8, 10])

## Broadcasting

In [53]:
l = [10,20,30,40]
arr = np.array(l)

In [54]:
arr + 10

array([20, 30, 40, 50])

In [55]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
arr2 = arr2 + 10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

## Deep And Shallow Copy

In [57]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
slice = a[:5]
slice = slice *10
slice

array([10, 20, 30, 40, 50])

In [59]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [60]:
a[4:6] *10 

array([50, 60])

In [61]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [62]:
b=a.copy()

In [63]:
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [64]:
b[0]

1

In [65]:
b[0]=99

In [66]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [67]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [68]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [69]:
A

array([[1, 2],
       [3, 4]])

In [70]:
B

array([[5, 6],
       [7, 8]])

In [81]:
A @ B

array([[19, 22],
       [43, 50]])

In [71]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [72]:
A

array([[1, 2],
       [3, 4]])

In [73]:
A.T

array([[1, 3],
       [2, 4]])

## ***Advanced Array Manipulation***

# Stacking array

In [74]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [75]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [76]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Splitting Array

In [78]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [79]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [80]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]